# Generated by Django 3.1.6 on 2021-02-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210213_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/profile_female.jpeg', upload_to='avatars'),
        ),
    ]
