# Generated by Django 3.1.5 on 2021-01-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20210130_1957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ammenity',
            new_name='Amenity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='ammenities',
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(to='rooms.Amenity'),
        ),
    ]
