# Generated by Django 3.1.5 on 2021-01-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20210131_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rooms.room'),
        ),
    ]
