# Generated by Django 3.1.5 on 2021-01-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20210131_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Room',
            new_name='room',
        ),
    ]
