# Generated by Django 3.1.5 on 2021-02-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('review', models.TextField()),
                ('accuracy', models.PositiveIntegerField()),
                ('communication', models.PositiveIntegerField()),
                ('cleanliness', models.PositiveIntegerField()),
                ('location', models.PositiveIntegerField()),
                ('check_in', models.PositiveIntegerField()),
                ('value', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
